name: Deploy

on:
  workflow_dispatch:
  release:
    tags:
      - v*

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        region: ["us-west-2", "us-east-1"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Deploy
        run: echo ${{ matrix.region }}
