name: Deploy

on:
  release:
    types: # This configuration does not affect the page_build event above
      - created
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        region: ["us-west-2", "us-east-1"]
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Deploy
        with:
          REGION: ${{ matrix.region }}
        run: |
          echo "$REGION"
